# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='author',
            new_name='user',
        ),
    ]
