# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import notes.models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=notes.models.get_image_filename, verbose_name='Image')),
                ('note', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
