# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(max_length=10000),
        ),
    ]
