# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0002_label_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
