# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0002_auto_20170510_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='archive',
            new_name='archived',
        ),
    ]
