# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0003_auto_20170510_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=0),
        ),
    ]
