# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0004_note_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pinned',
        ),
    ]
