# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:44
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0005_auto_20170509_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='background_color',
            field=colorful.fields.RGBColorField(default='#ffffff'),
        ),
        migrations.AlterField(
            model_name='label',
            name='text_color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
    ]
